name: Build

on: 
  push:
    branches:
      - master
      
jobs:   
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Build project
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
              node-version: '12.x'
      - run: npm ci
      - run: npm run build
