name: Build and deploy

on: 
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
              node-version: '12.x'
      - run: npm ci
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to server
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - run: ssh-keyscan -H ${{ secrets.APP_DOMEN }} >> ~/.ssh/known_hosts
      - run: rsync -avz ./.nuxt root@${{ secrets.APP_DOMEN }}:/var/www/${{ secrets.APP_DOMEN }}/
      - run: rsync -avz ./package.json root@${{ secrets.APP_DOMEN }}:/var/www/${{ secrets.APP_DOMEN }}/
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_DOMEN }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: npm i && npm run start
